// frontend/src/strings.js

export const strings = {
  en: {
    // Universal
    enterLocation: "Enter location...",
    changeLanguageButton: "Change Language",

    // Dashboard
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Key insights for your farm",
    quickActions: "Quick Actions",

    // Components
    chatTitle: "AI Assistant",
    chatbotButton: "AI Assistant",
    chatPlaceholder: "Ask about crops, soil, pests...",
    chatSend: "Send",
    chatNetworkError: "Network error. Please try again.",

    recommendTitle: "Crop Recommendation",
    recommendButton: "Crop Advice",
    recommendPrompt: "Enter your location to get crop recommendations.",
    getRecommendation: "Get Recommendation",
    gettingInfo: "Getting info...",
    recommendedCrops: "Recommended Crops",
    soilAndClimate: "Soil & Climate",
    recommendationError: "Could not fetch recommendation.",

    diseaseTitle: "Pest & Disease Detection",
    diseaseButton: "Detect Disease",
    diseasePrompt: "Upload an image of a crop to identify issues.",
    selectImage: "Select Image",
    analyzeImage: "Analyze Image",
    analyzing: "Analyzing...",
    analysisResult: "Analysis Result",
    health: "Health Score",
    cropIdentification: "Crop Identified",
    disease: "Disease/Pest",
    symptoms: "Symptoms",
    solutions: "Solutions",
    pesticidesAndPrevention: "Pesticides & Prevention",
    imageUploadSuccess: "Selected: ",
    selectFileFirst: "Please select an image first.",
    imageProcessingError: "Could not analyze the image.",

    weatherTitle: "Weather Advisory",
    weatherButton: "Weather",
    weatherPrompt: "Get weather forecasts and AI-powered farming alerts.",
    getWeather: "Get Weather",
    fetchingWeather: "Fetching...",
    currentWeather: "Current Weather",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    farmingAlerts: "AI Farming Alerts",
    dailyForecast: "7-Day Forecast",

    marketPricesTitle: "Market Prices",
    marketPricesButton: "Market Prices",
    marketPricesPrompt: "Check the latest market prices for your crops.",

    marketBroadcastTitle: "Today's Mandi Broadcast",
    marketCompare: "Compare Crop Prices Across States",
    marketState: "State",
    marketCrop: "Crop",
    marketResultsFor: "Results for",
    marketFillAll: "Please enter a crop and select at least one state.",


  },
  hi: {
    enterLocation: "स्थान दर्ज करें...",
    changeLanguageButton: "भाषा बदलें",
    dashboardTitle: "डैशबोर्ड",
    dashboardSubtitle: "आपके खेत के लिए मुख्य जानकारी",
    quickActions: "त्वरित कार्रवाई",
    chatTitle: "एआई सहायक",
    chatbotButton: "एआई सहायक",
    chatPlaceholder: "फसलों, मिट्टी, कीटों के बारे में पूछें...",
    chatSend: "भेजें",
    chatNetworkError: "नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।",
    recommendTitle: "फसल की सिफारिश",
    recommendButton: "फसल सलाह",
    recommendPrompt: "फसल की सिफारिशें प्राप्त करने के लिए अपना स्थान दर्ज करें।",
    getRecommendation: "सिफारिश प्राप्त करें",
    gettingInfo: "जानकारी मिल रही है...",
    recommendedCrops: "अनुशंसित फसलें",
    soilAndClimate: "मिट्टी और जलवायु",
    recommendationError: "सिफारिश प्राप्त नहीं हो सकी।",
    diseaseTitle: "कीट और रोग का पता लगाना",
    diseaseButton: "रोग का पता लगाएं",
    diseasePrompt: "समस्याओं की पहचान करने के लिए फसल की एक छवि अपलोड करें।",
    selectImage: "छवि चुनें",
    analyzeImage: "छवि का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    analysisResult: "विश्लेषण परिणाम",
    health: "स्वास्थ्य स्कोर",
    cropIdentification: "फसल की पहचान",
    disease: "रोग/कीट",
    symptoms: "लक्षण",
    solutions: "समाधान",
    pesticidesAndPrevention: "कीटनाशक और रोकथाम",
    imageUploadSuccess: "चयनित: ",
    selectFileFirst: "कृपया पहले एक छवि चुनें।",
    imageProcessingError: "छवि का विश्लेषण नहीं हो सका।",
    weatherTitle: "मौसम सलाह",
    weatherButton: "मौसम",
    weatherPrompt: "मौसम का पूर्वानुमान और एआई-संचालित खेती अलर्ट प्राप्त करें।",
    getWeather: "मौसम की जानकारी लें",
    fetchingWeather: "ला रहा है...",
    currentWeather: "वर्तमान मौसम",
    humidity: "नमी",
    windSpeed: "हवा की गति",
    farmingAlerts: "एआई खेती अलर्ट",
    dailyForecast: "7-दिन का पूर्वानुमान",
    marketPricesTitle: "बाजार मूल्य",
    marketPricesButton: "बाजार मूल्य",
    marketPricesPrompt: "अपनी फसलों के नवीनतम बाजार मूल्य की जाँच करें।",

    marketBroadcastTitle: "आज का मंडी प्रसारण",
    marketCompare: "राज्यों में फसल की कीमतों की तुलना करें",
    marketState: "राज्य",
    marketCrop: "फसल",
    marketResultsFor: "के लिए परिणाम",
    marketFillAll: "कृपया एक फसल दर्ज करें और कम से कम एक राज्य चुनें।",

  },
  pa: {
    enterLocation: "ਸਥਾਨ ਦਰਜ ਕਰੋ...",
    changeLanguageButton: "ਭਾਸ਼ਾ ਬਦਲੋ",
    dashboardTitle: "ਡੈਸ਼ਬੋਰਡ",
    dashboardSubtitle: "ਤੁਹਾਡੇ ਖੇਤ ਲਈ ਮੁੱਖ ਜਾਣਕਾਰੀ",
    quickActions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
    chatTitle: "ਏਆਈ ਸਹਾਇਕ",
    chatbotButton: "ਏਆਈ ਸਹਾਇਕ",
    chatPlaceholder: "ਫਸਲਾਂ, ਮਿੱਟੀ, ਕੀੜਿਆਂ ਬਾਰੇ ਪੁੱਛੋ...",
    chatSend: "ਭੇਜੋ",
    chatNetworkError: "ਨੈੱਟਵਰਕ ਗਲਤੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    recommendTitle: "ਫਸਲ ਦੀ ਸਿਫਾਰਸ਼",
    recommendButton: "ਫਸਲ ਸਲਾਹ",
    recommendPrompt: "ਫਸਲ ਦੀਆਂ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਸਥਾਨ ਦਰਜ ਕਰੋ।",
    getRecommendation: "ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ",
    gettingInfo: "ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਹੋ ਰਹੀ ਹੈ...",
    recommendedCrops: "ਸਿਫਾਰਸ਼ੀ ਫਸਲਾਂ",
    soilAndClimate: "ਮਿੱਟੀ ਅਤੇ ਜਲਵਾਯੂ",
    recommendationError: "ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕੀ।",
    diseaseTitle: "ਕੀੜੇ ਅਤੇ ਰੋਗ ਦੀ ਪਛਾਣ",
    diseaseButton: "ਰੋਗ ਦੀ ਪਛਾਣ ਕਰੋ",
    diseasePrompt: "ਸਮੱਸਿਆਵਾਂ ਦੀ ਪਛਾਣ ਕਰਨ ਲਈ ਫਸਲ ਦੀ ਇੱਕ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ।",
    selectImage: "ਤਸਵੀਰ ਚੁਣੋ",
    analyzeImage: "ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    analysisResult: "ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ",
    health: "ਸਿਹਤ ਸਕੋਰ",
    cropIdentification: "ਫਸਲ ਦੀ ਪਛਾਣ",
    disease: "ਰੋਗ/ਕੀੜੇ",
    symptoms: "ਲੱਛਣ",
    solutions: "ਹੱਲ",
    pesticidesAndPrevention: "ਕੀਟਨਾਸ਼ਕ ਅਤੇ ਰੋਕਥਾਮ",
    imageUploadSuccess: "ਚੁਣਿਆ ਗਿਆ: ",
    selectFileFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਇੱਕ ਤਸਵੀਰ ਚੁਣੋ।",
    imageProcessingError: "ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ।",
    weatherTitle: "ਮੌਸਮ ਸਲਾਹ",
    weatherButton: "ਮੌਸਮ",
    weatherPrompt: "ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਏਆਈ-ਸੰਚਾਲਿਤ ਖੇਤੀ ਚੇਤਾਵਨੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
    getWeather: "ਮੌਸਮ ਪ੍ਰਾਪਤ ਕਰੋ",
    fetchingWeather: "ਪ੍ਰਾਪਤ ਕਰ ਰਿਹਾ ਹੈ...",
    currentWeather: "ਮੌਜੂਦਾ ਮੌਸਮ",
    humidity: "ਨਮੀ",
    windSpeed: "ਹਵਾ ਦੀ ਗਤੀ",
    farmingAlerts: "ਏਆਈ ਖੇਤੀ ਚੇਤਾਵਨੀਆਂ",
    dailyForecast: "7-ਦਿਨ ਦੀ ਭਵਿੱਖਬਾਣੀ",
    marketPricesTitle: "ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ",
    marketPricesButton: "ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ",
    marketPricesPrompt: "ਆਪਣੀਆਂ ਫਸਲਾਂ ਦੀਆਂ ਨਵੀਨਤਮ ਬਾਜ਼ਾਰ ਕੀਮਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।",
  },
  mr: {
    enterLocation: "स्थान प्रविष्ट करा...",
    changeLanguageButton: "भाषा बदला",
    dashboardTitle: "डॅशबोर्ड",
    dashboardSubtitle: "तुमच्या शेतासाठी महत्त्वाची माहिती",
    quickActions: "त्वरित क्रिया",
    chatTitle: "एआय सहाय्यक",
    chatbotButton: "एआय सहाय्यक",
    chatPlaceholder: "पिके, माती, कीटक यांच्याबद्दल विचारा...",
    chatSend: "पाठवा",
    chatNetworkError: "नेटवर्क त्रुटी. कृपया पुन्हा प्रयत्न करा.",
    recommendTitle: "पीक शिफारस",
    recommendButton: "पीक सल्ला",
    recommendPrompt: "पीक शिफारसी मिळविण्यासाठी आपले स्थान प्रविष्ट करा.",
    getRecommendation: "शिफारस मिळवा",
    gettingInfo: "माहिती मिळत आहे...",
    recommendedCrops: "शिफारस केलेली पिके",
    soilAndClimate: "माती आणि हवामान",
    recommendationError: "शिफारस मिळू शकली नाही.",
    diseaseTitle: "कीड आणि रोग ओळख",
    diseaseButton: "रोग ओळखा",
    diseasePrompt: "समस्या ओळखण्यासाठी पिकाची एक प्रतिमा अपलोड करा.",
    selectImage: "प्रतिमा निवडा",
    analyzeImage: "प्रतिमेचे विश्लेषण करा",
    analyzing: "विश्लेषण होत आहे...",
    analysisResult: "विश्लेषण परिणाम",
    health: "आरोग्य गुण",
    cropIdentification: "पीक ओळख",
    disease: "रोग/कीड",
    symptoms: "लक्षणे",
    solutions: "उपाय",
    pesticidesAndPrevention: "कीटकनाशके आणि प्रतिबंध",
    imageUploadSuccess: "निवडले: ",
    selectFileFirst: "कृपया प्रथम एक प्रतिमा निवडा.",
    imageProcessingError: "प्रतिमेचे विश्लेषण करू शकलो नाही.",
    weatherTitle: "हवामान सल्ला",
    weatherButton: "हवामान",
    weatherPrompt: "हवामान अंदाज आणि एआय-आधारित शेती सूचना मिळवा.",
    getWeather: "हवामान मिळवा",
    fetchingWeather: "आणत आहे...",
    currentWeather: "सध्याचे हवामान",
    humidity: "आर्द्रता",
    windSpeed: "वाऱ्याचा वेग",
    farmingAlerts: "एआय शेती सूचना",
    dailyForecast: "७-दिवसांचा अंदाज",
    marketPricesTitle: "बाजारभाव",
    marketPricesButton: "बाजारभाव",
    marketPricesPrompt: "तुमच्या पिकांचे नवीनतम बाजारभाव तपासा.",
  }
};